services:
  - type: web
    name: duermechill-backend
    env: docker
    rootDir: duermechill-Backend
    plan: free
    autoDeploy: true

  - type: web
    name: duermechill-frontend
    env: node
    rootDir: duermechill-Fronted
    plan: free
    buildCommand: |
      git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
      export PATH="$HOME/flutter/bin:$PATH"
      flutter config --enable-web
      flutter pub get
      flutter build web --release
    startCommand: cd build/web && python -m http.server $PORT
    autoDeploy: true
